### ISSUE TITLE
Question about a new use case

### ISSUE THREAD

**Issue by cpatrickalves** [csinva/matching-with-gans#6]
Hi there, 

Thanks for sharing this great project.

I am working on a project to generate images with some conditions (acne, wrinkles, redness, etc.).

I've used stylegan2-ADA to build a model that generates faces with acne. 

Now, I need to control the severity level of acne controlling generation processing. 

I've tried exploring latent space with [Ganspace](https://github.com/harskish/ganspace) and other projects with no success.

How do you control the AGE and other features? have you mapped the latent vectors?

**Comment by csinva** [comment]
Thanks for your interest!

Indeed, we had to explicitly map the latent vectors, by collecting annotations of different attributes and then learning linear models to predict them in the latent space (annotations [here](https://github.com/csinva/matching-with-gans/blob/master/data/annotations_stylegan2/readme.md), method description [here](https://arxiv.org/abs/2007.06570)). Unfortunately it requires quite a lot of human labeling.

**Comment by cpatrickalves** [comment]
Thanks for the answer!
